### ISSUE TITLE
Crashes after opening the game in Android

### ISSUE THREAD

**Issue by 3squ** [oatmealine/nlw-integration#1]
I deleted my mods folder and only include Custom Name mod on the video, but I'm sure it crashed with this only mod installed aside from nodeids.
[Geode 2024-02-05 16.40.11.log](https://github.com/oatmealine/nlw-integration/files/14162518/Geode.2024-02-05.16.40.11.log)

https://github.com/oatmealine/nlw-integration/assets/157225967/f39075c6-c0c5-4b74-b130-bcfa0395661e

**Comment by oatmealine** [comment]
thank you for the report - i'm aware of the issue but have been struggling to figure out why it happens
could you please attach the file listed here? it'd help a lot w/ figuring out the issue
> Geode crashed! Crash dump saved to /storage/emulated/0/Android/media/com.geode.launcher/game/geode/crashlogs/ba38b198-795e-4aab-23ffeb97-7c275d93.dmp

**Comment by oatmealine** [comment]
fixed in 239e5e5, fixed server-side in [`96ee81f77d`](https://git.oat.zone/oat/nlw-api/commit/96ee81f77deddf8f44387c4f683323a79dee314f). hopefully will never happen again
