### ISSUE TITLE
Problem with not listed insane demons.

### ISSUE THREAD

**Issue by fedew04** [oatmealine/nlw-integration#2]
Insane demons that are not yet in the spreadsheet all show the details of "ApocalypseAfterParty", the first demon in the spreadsheet. You can replicate this bug by searching for Robot King and EdenCity, both of them insane demons that are not in the spreadsheet. Hopefully you can make it so if the demon is not found in the spreadsheet it just doesn't show anything. I'm on android btw, no idea if this happens on PC.

**Comment by oatmealine** [comment]
fixed in 9bef4291197b8c9ac18b501848bb614f1e1d192b
