### ISSUE TITLE
Descriptions Appear Blank

### ISSUE THREAD

**Issue by MasterGamerY** [oatmealine/nlw-integration#3]
The box for the description of the level appears blank.
![20240225181050_1](https://github.com/oatmealine/nlw-integration/assets/157644374/2943a851-3881-4337-8f46-04c2497422d1)

**Comment by oatmealine** [comment]
known; a lot is broken because of NLW changes, will get to soon

**Comment by oatmealine** [comment]
fixed in [8550458ff1](https://git.oat.zone/oat/nlw-api/commit/8550458ff103a28ed10bcab7c1cb0042a88ac6a4)
